# Generated by Django 2.2.9 on 2020-09-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm_primer', '0002_operator_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='station',
        ),
        migrations.CreateModel(
            name='Work_in_station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator', to='orm_primer.Operator')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station', to='orm_primer.Station')),
            ],
        ),
    ]
